name: Android CI
on:
  push:
    branches: [ "principal", "main" ]
  pull_request:
    branches: [ "principal", "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: android-actions/setup-android@v3
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.9
      - name: Build APK debug
        run: gradle :aplicación:assembleDebug
      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: HolaAndroid-debug
          path: aplicación/build/outputs/apk/debug/*.apk
